# Generated by Django 3.2.10 on 2022-01-04 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Event ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('start_date', models.DateTimeField(verbose_name='Start data')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('repetition_term', models.PositiveSmallIntegerField(choices=[(1, 'One-Time'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=1, verbose_name='Repetition term')),
                ('privacy_status', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1, verbose_name='Privacy status')),
                ('participant_limit', models.PositiveIntegerField(default=0, verbose_name='Participant limit')),
                ('participant_picking', models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Pick participants')], default=1, verbose_name='Participant picking')),
                ('cancelled', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0, max_length=1, verbose_name='Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Event owner')),
            ],
        ),
        migrations.CreateModel(
            name='EventRate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Event rate ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')], verbose_name='Event rate value')),
                ('content', models.TextField(verbose_name='Member comment for event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Attended event')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member attending to the event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Event attendance request ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (2, 'Declined'), (3, "Waiting for event owner's approval")], default=3, verbose_name='Event attendance request status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event requested to attend')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member requesting to attend to the event')),
            ],
        ),
    ]
