# Generated by Django 3.2.10 on 2021-12-30 01:08

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
        migrations.DeleteModel(
            name='EventLocation',
        ),
    ]
