# Generated by Django 3.2.10 on 2021-12-30 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20211230_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Event rate ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Excellent')], verbose_name='Event rate value')),
                ('content', models.TextField(verbose_name='Member comment for event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Attended event')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member attending to the event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Event attendance request ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (2, 'Declined'), (3, "Waiting for event owner's approval")], default=3, verbose_name='Event attendance request status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event requested to attend')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member requesting to attend to the event')),
            ],
        ),
    ]
