version: "3.9"
   
services:
  swe578_web:
    container_name: swe578-web
    build: ./etc/docker/web
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    # bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - swe578_mariadb
  swe578_mariadb:
    container_name: swe578-mariadb
    build: ./etc/docker/mariadb
    volumes:
      - ./etc/docker/mariadb/config:/etc/mysql/conf.d
    env_file:
      - ./etc/docker/mariadb/env/common.env
    ports:
      - "28001:3306"
