# Generated by Django 3.2.10 on 2021-12-30 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Service ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Service description')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('start_date', models.DateTimeField(verbose_name='Start data')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('repetition_term', models.PositiveSmallIntegerField(choices=[(1, 'One-Time'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], default=1, verbose_name='Repetition term')),
                ('privacy_status', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1, verbose_name='Privacy status')),
                ('participant_limit', models.PositiveIntegerField(default=0, verbose_name='Participant limit')),
                ('participant_picking', models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Pick participants')], default=1, verbose_name='Participant picking')),
                ('content', models.TextField(verbose_name='Service content')),
                ('cancelled', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0, max_length=1, verbose_name='Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Service owner')),
            ],
        ),
    ]
