# Generated by Django 3.2.10 on 2022-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='end_date',
        ),
        migrations.AddField(
            model_name='service',
            name='credit',
            field=models.PositiveIntegerField(default=2, verbose_name='Credit'),
        ),
    ]
