# Generated by Django 3.2.11 on 2022-01-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220105_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='credit',
            field=models.PositiveIntegerField(verbose_name='Credit'),
        ),
    ]
