# Generated by Django 3.2.11 on 2022-01-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20220105_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created_at']},
        ),
    ]
