# Generated by Django 3.2.11 on 2022-01-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.TextField(),
        ),
    ]
