# Generated by Django 3.2.11 on 2022-01-07 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0011_remove_serviceattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceattendancerequest',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Member to approve'),
        ),
        migrations.AlterField(
            model_name='serviceattendancerequest',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_requested', to=settings.AUTH_USER_MODEL, verbose_name='Member requesting to attend to the service'),
        ),
    ]
