# Generated by Django 3.2.11 on 2022-01-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0012_auto_20220107_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceattendance',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_owner', to=settings.AUTH_USER_MODEL, verbose_name='Member to approve'),
        ),
        migrations.AlterField(
            model_name='serviceattendance',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_attending', to=settings.AUTH_USER_MODEL, verbose_name='Member attending to the service'),
        ),
    ]
