# Generated by Django 3.2.11 on 2022-01-07 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0013_auto_20220107_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_attending', to=settings.AUTH_USER_MODEL, verbose_name='Member attending to the service'),
        ),
        migrations.AlterField(
            model_name='serviceattendance',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_owner', to=settings.AUTH_USER_MODEL, verbose_name='Member to approve'),
        ),
        migrations.AlterField(
            model_name='serviceattendance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Attended service'),
        ),
        migrations.AlterField(
            model_name='serviceattendancerequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_requested', to=settings.AUTH_USER_MODEL, verbose_name='Member requesting to attend to the service'),
        ),
        migrations.AlterField(
            model_name='serviceattendancerequest',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Member to approve'),
        ),
        migrations.AlterField(
            model_name='serviceattendancerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service requested to attend'),
        ),
    ]
