# Generated by Django 3.2.11 on 2022-01-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20220107_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceattendancerequest',
            options={'ordering': ['created_at']},
        ),
    ]
