# Generated by Django 3.2.11 on 2022-01-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_serviceattendancerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
