# Generated by Django 3.2.11 on 2022-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_serviceattendance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
