# Generated by Django 3.2.11 on 2022-01-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivered',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0, max_length=1, verbose_name='Delivered'),
        ),
    ]
