# Generated by Django 3.2.11 on 2022-01-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20220108_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Member comment for service'),
        ),
    ]
