# Generated by Django 3.2.11 on 2022-01-09 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_servicerate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceattendance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='services.service', verbose_name='Attended service'),
        ),
    ]
