# Generated by Django 3.2.10 on 2021-12-29 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Member Location ID')),
                ('name', models.CharField(max_length=500, verbose_name='Location name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.TextField(verbose_name='Member address')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Member ID')),
                ('first_name', models.CharField(max_length=500, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=500, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=500, verbose_name='Phone number')),
                ('personal_characteristics', models.TextField(verbose_name='Personal characteristics')),
                ('bio', models.TextField(verbose_name='Short bio')),
                ('talents', models.TextField(verbose_name='Talents')),
                ('credit', models.PositiveIntegerField(verbose_name='Total credits')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberlocation', verbose_name='Location')),
            ],
        ),
    ]
