# Generated by Django 3.2.10 on 2021-12-29 14:18

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20211229_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
