# Generated by Django 3.2.10 on 2021-12-30 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDirectedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to=settings.AUTH_USER_MODEL, verbose_name='Member following')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL, verbose_name='Member followed')),
            ],
        ),
        migrations.DeleteModel(
            name='MemberLocation',
        ),
    ]
