# Generated by Django 3.2.11 on 2022-01-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20220111_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='members/'),
        ),
    ]
