# Generated by Django 3.2.11 on 2022-01-11 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_memberprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
